// src/config/worlds.config.js
export const WORLDS = [
  {
    id: 0,
    name: 'Coin Corner',
    emoji: '🪙',
    accent: '#FFD700',
    description: 'Count 5¢ and 10¢ coins — the basics of money!',
    conceptFocus: 'count_small_coins',
    boss: { name: 'Coin Keeper',    emoji: '🪙', reward: 'Coin Expert Badge 🪙' },
  },
  {
    id: 1,
    name: 'Market Stall',
    emoji: '🍎',
    accent: '#FF6F61',
    description: "Count 20¢ and 50¢ coins at Emma's stall",
    conceptFocus: 'count_mixed_coins',
    boss: { name: 'Stall Boss',     emoji: '🍉', reward: 'Market Star Badge 🍎' },
  },
  {
    id: 2,
    name: 'Note Bank',
    emoji: '💵',
    accent: '#4CAF50',
    description: 'Recognise and count $1, $2, $5, $10 notes',
    conceptFocus: 'count_notes',
    boss: { name: 'Banker Boss',    emoji: '🏦', reward: 'Note Master Badge 💵' },
  },
  {
    id: 3,
    name: 'Mixed Money Mart',
    emoji: '🛍️',
    accent: '#AB47BC',
    description: 'Count collections of mixed coins and notes (up to $5)',
    conceptFocus: 'count_mixed_collection',
    boss: { name: 'Market Boss',    emoji: '🛒', reward: 'Mart Champion Badge 🛍️' },
  },
  {
    id: 4,
    name: 'Cents to Dollars',
    emoji: '💱',
    accent: '#29B6F6',
    description: 'Convert between cents and dollars — 100¢ = $1!',
    conceptFocus: 'conversion',
    boss: { name: 'Exchange Boss',  emoji: '💱', reward: 'Converter Badge 💱' },
  },
  {
    id: 5,
    name: 'Which is More?',
    emoji: '⚖️',
    accent: '#EC407A',
    description: 'Compare and order money amounts',
    conceptFocus: 'compare',
    boss: { name: 'Scale Boss',     emoji: '⚖️', reward: 'Comparison Badge ⚖️' },
  },
  {
    id: 6,
    name: 'Adding Money',
    emoji: '➕',
    accent: '#FF9800',
    description: 'Add two money amounts in dollars and cents',
    conceptFocus: 'addition',
    boss: { name: 'Calculator Boss', emoji: '🧮', reward: 'Adding Pro Badge ➕' },
  },
  {
    id: 7,
    name: 'Making Change',
    emoji: '🔄',
    accent: '#26A69A',
    description: 'Subtract to find change from $1, $2, or $5',
    conceptFocus: 'change',
    boss: { name: 'Change Boss',    emoji: '💸', reward: 'Change Champion Badge 🔄' },
  },
  {
    id: 8,
    name: 'Word Problem Market',
    emoji: '📝',
    accent: '#5C6BC0',
    description: 'Solve money word problems — buy, change, how much more',
    conceptFocus: 'word_problems',
    boss: { name: 'Problem Boss',   emoji: '🧩', reward: 'Problem Solver Badge 📝' },
  },
  {
    id: 9,
    name: 'Money Master',
    emoji: '🏆',
    accent: '#FFC107',
    description: 'Master all money skills — the ultimate challenge!',
    conceptFocus: 'mixed_review',
    boss: { name: 'Money King',     emoji: '👑', reward: 'Money Master Badge 👑' },
  },
];

export const PLAY_MODES = [
  {
    id: 'guided',
    name: 'Guided Practice',
    icon: '🧭',
    desc: '5 questions with hints, no time pressure',
    questionCount: 5,
    hints: true,
    timed: false,
    lives: false,
  },
  {
    id: 'independent',
    name: 'Independent Practice',
    icon: '✍️',
    desc: '10 questions, no hints, full XP',
    questionCount: 10,
    hints: false,
    timed: false,
    lives: false,
  },
  {
    id: 'timed',
    name: 'Timed Challenge',
    icon: '⏱️',
    desc: '8 questions in 60 seconds, bonus XP',
    questionCount: 8,
    hints: false,
    timed: true,
    timeLimit: 60,
    lives: false,
  },
  {
    id: 'boss',
    name: 'Boss Battle',
    icon: '👑',
    desc: '5 questions, 3 lives — defeat the boss!',
    questionCount: 5,
    hints: false,
    timed: false,
    lives: true,
  },
];

export const BADGES = [
  { id: 'first_coin',    name: 'First Coin',         icon: '🏅', desc: 'First correct money answer' },
  { id: 'hot_streak',    name: 'Hot Streak',          icon: '🔥', desc: '5 consecutive correct answers' },
  { id: 'change_champ',  name: 'Change Champion',     icon: '🥈', desc: 'Completed all Simulate stations' },
  { id: 'money_master',  name: 'Money Master',        icon: '🥇', desc: '80%+ correct across any world' },
  { id: 'perfect_purse', name: 'Perfect Purse',       icon: '💎', desc: 'Perfect score in any world' },
  { id: 'boss_slayer',   name: 'Boss Slayer',         icon: '👑', desc: 'Defeated any Boss Battle' },
  { id: 'full_journey',  name: 'Full Journey',        icon: '🌟', desc: 'Completed every phase' },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 20,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};

export const COINS  = [5, 10, 20, 50, 100];
export const NOTES  = [100, 200, 500, 1000];
export const DENOMS = [...COINS, ...NOTES];
